# Generated by Django 4.2.5 on 2024-01-01 09:10

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(null=True, upload_to='api/statics/userimages/')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(db_index=True, editable=False, max_length=6, unique=True)),
                ('open_till', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today), django.core.validators.MaxValueValidator(datetime.timedelta(days=5))])),
                ('votes_to_skip_or_pause', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='api.user')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('participants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.user')),
            ],
        ),
    ]
